### PR TITLE
Fix Sleeping, voltage and temperature readings

### LINKED ISSUE #1590: Sleeping, CPU voltage and CPU temperature readings not working on STM32F1

### PR DESCRIPTION
**Pull request by tekka007**
Fix #1590

### CODE REVIEW

File: hal/architecture/STM32/MyHwSTM32.cpp [hunk 1]
```diff
@@ -128,145 +138,262 @@ void hwReboot(void)
...
-	// Note: Requires calibration values for accurate results
-
-	int32_t temp_raw = analogRead(ATEMP);
+	int32_t temp_raw = hwReadInternalTemp();
 
-#ifdef TEMP110_CAL_ADDR
-	// Use factory calibration if available (STM32F4, L4, etc.)
-	uint16_t *temp30_cal = (uint16_t *)TEMP30_CAL_ADDR;
-	uint16_t *temp110_cal = (uint16_t *)TEMP110_CAL_ADDR;
+	if (temp_raw < 0) {
```
Comment (fallberg) [inline hal/architecture/STM32/MyHwSTM32.cpp]: **Reporter**: Cppcheck
**Rule**: knownConditionTrueFalse
**Severity**: INFO
**File**: hal/architecture/STM32/MyHwSTM32.cpp L329

Condition &#39;temp_raw&lt;0&#39; is always true

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-969273324>*

File: hal/architecture/STM32/MyHwSTM32.cpp [hunk 2]
```diff
@@ -128,145 +138,262 @@ void hwReboot(void)
...
 }
 
 int8_t hwCPUTemperature(void)
 {
-#if defined(TEMP_SENSOR_AVAILABLE) && defined(ATEMP) && defined(__HAL_RCC_ADC1_CLK_ENABLE)
-	// Read internal temperature sensor
-	// Note: Requires calibration values for accurate results
-
-	int32_t temp_raw = analogRead(ATEMP);
+	int32_t temp_raw = hwReadInternalTemp();
```
Comment (fallberg) [inline hal/architecture/STM32/MyHwSTM32.cpp]: **Reporter**: Cppcheck
**Rule**: knownConditionTrueFalse
**Severity**: INFO
**File**: hal/architecture/STM32/MyHwSTM32.cpp L327

Condition &#39;temp_raw&lt;0&#39; is always true. Assignment &#39;temp_raw&#61;hwReadInternalTemp()&#39;, assigned value is -1

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1545837729>*
